### ISSUE TITLE
Hold builds if another build on the same branch is still active

### ISSUE THREAD

**Issue by mbertheau** [or/jeeves#2]

**Comment by or** [comment]
By the way, Jeeves could compare the scripts of two builds and if they are identical, then queued up builds can be safely collapsed into one. If `{commit}` is used in the script (just added it to the context), then the scripts will differ and two builds are correct.

**Comment by mbertheau** [comment]
This sounds like a nice way to do it!

**Comment by or** [comment]
Took a similar but more flexible (and I think intuitive) approach now. A ` blocking_key_template` in the Project configuration will be used with the same context that is passed to the script, the result is stored in ` Build.blocking_key`  and a build is blocked by the most recent unfinished build in that project with the same `blocking_key`.

If a build is cancelled or finished, then all builds blocked by it (there actually should be only one) are rescheduled.

Fixed by 77878f2ad8a8f9192b68476cbf5a70225dc45f9f.
